<a href="https://colab.research.google.com/github/mocamocamo/inflearn-llm-colab/blob/main/1_tokenizing%EA%B3%BC_one_hot_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. tokenizing과 one-hot-encoding

In [1]:
!pip install nltk

In [2]:
import nltk

In [3]:
nltk.download("all", quiet=True)

True

In [4]:
from numpy import array, argmax
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# one-hot-encoding 예제
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warn', 'cold', 'warm', 'hot']
print(set(data))
values = array(data)
print(values)

# integer encoding 예제
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
print(integer_encoded.shape)

{'hot', 'cold', 'warm', 'warn'}
['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warn' 'cold' 'warm' 'hot']
[0 0 2 0 1 1 3 0 2 1]
(10,)


In [5]:
# one-hot-encoding 예제
onehot_encoder = OneHotEncoder(sparse_output=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
print(integer_encoded.reshape(len(integer_encoded), 1))
print(integer_encoded.shape)

onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)


[[0]
 [0]
 [2]
 [0]
 [1]
 [1]
 [3]
 [0]
 [2]
 [1]]
(10, 1)
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]


In [6]:
# one-hot-encoding을 다시 string 형태로 변경
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

inverted = label_encoder.inverse_transform([argmax(onehot_encoded[1, :])])
print(inverted)

inverted = label_encoder.inverse_transform([argmax(onehot_encoded[2, :])])
print(inverted)

['cold']
['cold']
['warm']
